# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  [
    '-p',
    'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )',
    __dir__
  ]
).strip

platform :ios, min_ios_version_supported

prepare_react_native_project!

target 'DriverApp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Maps
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix for React-Fabric Libtool errors with static frameworks
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Enable BUILD_LIBRARY_FOR_DISTRIBUTION for all pods
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        
        # Fix architecture settings
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        
        # Fix for React-Fabric and other React pods
        if target.name == 'React-Fabric' || target.name.start_with?('React-')
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
          config.build_settings['OTHER_LDFLAGS'] << '-ObjC'
          config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
        
        # Fix deployment target
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.4
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        end
      end
    end
  end
end
